### ISSUE TITLE
Pick to dev tools

### ISSUE THREAD

**Issue by balsamiqMichele** [Altariel/blqchatgptexperiments#2]
Express, nextjs, solid, MUI?

**Comment by balsamiqMichele** [comment]
My takes on Tools

* nextjs https://www.udemy.com/course/nextjs-react-the-complete-guide/
* MUI https://www.youtube.com/playlist?list=PLDxCaNaYIuUlG5ZqoQzFE27CUOoQvOqnQ

**Comment by balsamiqLuca** [comment]
We decided to use MUI and Next.JS
